
const BACKGROUND = {
    "bg0": {
        "layer0": 'assets/img/background/Battleground1/Bright/sky.png',
        "layer1": 'assets/img/background/Battleground1/Bright/ruins_bg.png',
        "layer2": 'assets/img/background/Battleground1/Bright/hills&trees.png',
        "layer3": 'assets/img/background/Battleground1/Bright/ruins2.png',
        "layer4": 'assets/img/background/Battleground1/Bright/statue.png',
        "layer5": 'assets/img/background/Battleground1/Bright/ruins.png',
        "layer6": 'assets/img/background/Battleground1/Bright/stones&grass.png',
    },
    "bg1": {
        "layer0": 'assets/img/background/Battleground1/Pale/sky.png',
        "layer1": 'assets/img/background/Battleground1/Pale/ruins_bg.png',
        "layer2": 'assets/img/background/Battleground1/Pale/hills&trees.png',
        "layer3": 'assets/img/background/Battleground1/Pale/ruins2.png',
        "layer4": 'assets/img/background/Battleground1/Pale/statue.png',
        "layer5": 'assets/img/background/Battleground1/Pale/ruins.png',
        "layer6": 'assets/img/background/Battleground1/Pale/stones&grass.png',
    },
    "bg2": {
        "layer0": 'assets/img/background/Battleground3/Bright/sky.png',
        "layer1": 'assets/img/background/Battleground3/Bright/jungle_bg.png',
        "layer2": 'assets/img/background/Battleground3/Bright/trees&bushes.png',
        "layer3": 'assets/img/background/Battleground3/Bright/grasses.png',
        "layer4": 'assets/img/background/Battleground3/Bright/grass&road.png',
        "layer5": 'assets/img/background/Battleground3/Bright/lianas.png',
        "layer6": 'assets/img/background/Battleground3/Bright/tree_face.png',
    },
    "bg3": {
        "layer0": 'assets/img/background/Battleground3/Pale/sky.png',
        "layer1": 'assets/img/background/Battleground3/Pale/jungle_bg.png',
        "layer2": 'assets/img/background/Battleground3/Pale/trees&bushes.png',
        "layer3": 'assets/img/background/Battleground3/Pale/grasses.png',
        "layer4": 'assets/img/background/Battleground3/Pale/grass&road.png',
        "layer5": 'assets/img/background/Battleground3/Pale/lianas.png',
        "layer6": 'assets/img/background/Battleground3/Pale/tree_face.png',
    },
    "bg4": {
        "layer0": 'assets/img/background/Battleground4/Bright/sky.png',
        "layer1": 'assets/img/background/Battleground4/Bright/graves.png',
        "layer2": 'assets/img/background/Battleground4/Bright/back_trees.png',
        "layer3": 'assets/img/background/Battleground4/Bright/crypt.png',
        "layer4": 'assets/img/background/Battleground4/Bright/wall.png',
        "layer5": 'assets/img/background/Battleground4/Bright/ground.png',
        "layer6": 'assets/img/background/Battleground4/Bright/bones.png',
    },
    "bg5": {
        "layer0": 'assets/img/background/Battleground4/Pale/sky.png',
        "layer1": 'assets/img/background/Battleground4/Pale/graves.png',
        "layer2": 'assets/img/background/Battleground4/Pale/back_trees.png',
        "layer3": 'assets/img/background/Battleground4/Pale/crypt.png',
        "layer4": 'assets/img/background/Battleground4/Pale/wall.png',
        "layer5": 'assets/img/background/Battleground4/Pale/ground.png',
        "layer6": 'assets/img/background/Battleground4/Pale/bones.png',
    },
    "bg6": {
        "layer0": 'assets/img/background/Battleground2/Bright/bg.png',
        "layer1": 'assets/img/background/Battleground2/Bright/mountaims.png',
        "layer2": 'assets/img/background/Battleground2/Bright/wall@windows.png',
        "layer3": 'assets/img/background/Battleground2/Bright/columns&falgs.png',
        "layer4": 'assets/img/background/Battleground2/Bright/candeliar.png',
        "layer5": 'assets/img/background/Battleground2/Bright/dragon.png',
        "layer6": 'assets/img/background/Battleground2/Bright/floor.png',
    },
    "bg7": {
        "layer0": 'assets/img/background/Battleground2/Pale/bg.png',
        "layer1": 'assets/img/background/Battleground2/Pale/mountaims.png',
        "layer2": 'assets/img/background/Battleground2/Pale/wall@windows.png',
        "layer3": 'assets/img/background/Battleground2/Pale/columns&falgs.png',
        "layer4": 'assets/img/background/Battleground2/Pale/candeliar.png',
        "layer5": 'assets/img/background/Battleground2/Pale/dragon.png',
        "layer6": 'assets/img/background/Battleground2/Pale/floor.png',
    },
}