let language = {
    'german': {
        'switchLanguageTo': 'english',
        'empty': '',
        'mainMenuButton1': 'Spiel',
        'mainMenuButton2': 'Einstellungen',
        'mainMenuButton3': 'Spielanleitung',
        'mainMenuButton4': 'Rechtliches',
        'settingsMenuPanel1': 'Lautstärke',
        'settingsMenuPanel2': 'Soundeffekte',
        'settingsMenuButton1': '+',
        'settingsMenuButton2': '-',
        'settingsMenuButton3': 'Zurück',
        'settingsMenuButton4': 'Ton stummschalten',
        'settingsMenuButton5': 'Wechsel zu Englisch',
        'legalMenuButton1': 'Impressum',
        'legalMenuButton2': 'Datenschutz',
        'legalMenuButton3': 'Zurück',
        'gameMenuButton1': 'Spiel starten',
        'gameMenuButton2': 'Spiel laden',
        'gameMenuButton3': 'Spiel speichern',
        'gameMenuButton4': 'Zurück',
        'loadgameMenuPanel1': 'Geladen',
        'loadgameMenuButton1': 'Laden',
        'loadgameMenuButton2': 'Zurück',
        'savegameMenuButton1': 'Speichern',
        'savegameMenuButton2': 'Zurück',
        'gamecontrollMenuPanel1': 'Level',
        'gamecontrollMenuPanel2': 'Erschwernis',
        'gamecontrollMenuButton1': 'Spielen',
        'gamecontrollMenuButton2': 'Fähigkeiten',
        'gamecontrollMenuButton3': '+',
        'gamecontrollMenuButton4': '-',
        'gamecontrollMenuButton5': 'Zurück',
        'skillsMenuPanael1': 'Verfügbare Münzen',
        'skillsMenuButton1': 'Zurück',
        'victoryPageMenuPanel1': 'Verdiente Münzen',
        'victoryPageMenuPanel2': 'Neues Level freigeschaltet',
        'victoryPageMenuPanel3': 'Neue Schwierigkeit freigeschaltet',
        'victoryPageButton1': 'Sieg',
        'losePageMenuPanel1': 'Du wurdest besiegt',
        'losePageMenuButton1': 'Erneut versuchen',
        'controllsMenuPanel1': 'W  =  Springen',
        'controllsMenuPanel2': 'D  =  Nach rechts bewegen',
        'controllsMenuPanel3': 'A  =  Nach links bewegen',
        'controllsMenuPanel4': 'S  =  Schild heben',
        'controllsMenuPanel5': 'Leertaste  =  Angriff',
        'wideScreenNotification': 'Drehe in Querformat'
    },
    'english': {
        'switchLanguageTo': 'german',
        'empty': '',
        'mainMenuButton1': 'Game',
        'mainMenuButton2': 'Setting',
        'mainMenuButton3': 'How to Play',
        'mainMenuButton4': 'Legal',
        'settingsMenuPanel1': 'Volume',
        'settingsMenuPanel2': 'SFX',
        'settingsMenuButton1': '+',
        'settingsMenuButton2': '-',
        'settingsMenuButton3': 'Back',
        'settingsMenuButton4': 'Mute Sound',
        'settingsMenuButton5': 'Switch to German',
        'legalMenuButton1': 'legal notice',
        'legalMenuButton2': 'privat polecey',
        'legalMenuButton3': 'Back',
        'gameMenuButton1': 'Start Game',
        'gameMenuButton2': 'Load Game',
        'gameMenuButton3': 'Save Game',
        'gameMenuButton4': 'Back',
        'loadgameMenuPanel1': 'Loaded',
        'loadgameMenuButton1': 'Load',
        'loadgameMenuButton2': 'Back',
        'savegameMenuButton1': 'Save',
        'savegameMenuButton2': 'Back',
        'gamecontrollMenuPanel1': 'Level',
        'gamecontrollMenuPanel2': 'Difficulty',
        'gamecontrollMenuButton1': 'Play',
        'gamecontrollMenuButton2': 'Skills',
        'gamecontrollMenuButton3': '+',
        'gamecontrollMenuButton4': '-',
        'gamecontrollMenuButton5': 'Back',
        'skillsMenuPanael1': 'available coins',
        'skillsMenuButton1': 'Back',
        'victoryPageMenuPanel1': 'Coins earnd',
        'victoryPageMenuPanel2': 'Unlock new Stage',
        'victoryPageMenuPanel3': 'Unlock new Difficulty',
        'victoryPageButton1': 'Victroy',
        'losePageMenuPanel1': 'you were defeated',
        'losePageMenuButton1': 'Try again',
        'controllsMenuPanel1': 'W  =  Jump',
        'controllsMenuPanel2': 'D  =  Move right',
        'controllsMenuPanel3': 'A  =  Move Left',
        'controllsMenuPanel4': 'S  =  Raise Shield',
        'controllsMenuPanel5': 'Space  =  Attack',
        'wideScreenNotification': 'turn to Landscape'
    }
}